# .readthedocs.yaml

version: 2  # Configuration file format version

# Sphinx configuration
sphinx:
  configuration: docs/conf.py  # Path to the Sphinx configuration file

# Python version and dependencies
python:
  version: "3.9"  # Use Python 3.9 for building documentation
  install:
    - requirements: docs/requirements.txt  # Install dependencies from this file

# Build formats
formats:
  - html  # Build HTML documentation for web viewing
  - pdf   # Optional: Generate a downloadable PDF version
  - epub  # Optional: Generate an ePub version for e-readers

# Custom build commands (optional)
build:
  commands:
    - echo "Building the Teloz Website documentation..."
